version: '3.5'

services:
  alfred_commute_service:
    build: .
    image: alfred_commute_service:latest
    container_name: alfred_commute_service
    restart: always
    hostname: alfred_commute_service
    networks:
      - alfred
    ports:
      - '3985:3978'
    command: npm run local

networks:
  alfred:
    name: alfred
    driver: bridge
